spring:
  profiles:
    active: "dev"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
      client:
        registration:
          keycloak:
            client-id: spring-boot-client
            client-secret: <your-client-secret>
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/myrealm
server:
  port: 9090