spring:
  application:
    name: ms-users
  profiles:
    active: "docker"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/myrealm
          jwk-set-uri: http://localhost:8080/realms/myrealm/.well-known/openid-configuration
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/myrealm
server:
  port: 9090
